### ISSUE TITLE
没事儿不要乱改Array.prototype上的方法

### ISSUE THREAD

**Issue by wskongdesheng** [qixin1991/koa-router-xls#2]
没事儿不要乱改Array.prototype上的方法
这包导致整个项目的Array.prototype.find出错，麻烦看下吧

**Comment by qixin1991** [comment]
@wskongdesheng 项目里就一个`index.js`文件，发issue之前看下代码有没有你说的改动就知道了。你的项目出错，请提供下详细的错误信息，确认下是不是其它第三方库引起。
